language: php

# Versions of PHP you want your project run with.
php:
  - 8.1

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - phpenv config-rm xdebug.ini

# Commands you want to run that will verify your build.s
script:
  - mkdir -p logs/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always

after_success:
  - travis_retry php vendor/bin/php-coveralls
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v